__all__ = (
    'GENSHIN_IMPACT',
    'ART_STYLE',
    'CLOTHING',
    'JEWELRY',
    'EMOTIONS',
    'BODY'
)


GENSHIN_IMPACT = {
    'геншин': 'genshin_impact',
    'розария': 'rosaria_(genshin_impact)',
    'хутао': 'hu_tao_(genshin_impact)',
    'сяо': 'xiao_(genshin_impact)',
    'ганьюй': 'ganyu_(genshin_impact)',
    'альбедо': 'albedo_(genshin_impact)',
    'чжунли': 'zhongli_(genshin_impact)',
    'синьянь': 'xinyan_(genshin_impact)',
    'тарталья': 'tartaglia_(genshin_impact)',
    'диона': 'diona_(genshin_impact)',
    'кли': 'klee_(genshin_impact)',
    'венти': 'venti_(genshin_impact)',
    'кэцин': 'keqing_(genshin_impact)',
    'мона': 'mona_(genshin_impact)',
    'цици': 'qiqi_(genshin_impact)',
    'дилюк': 'diluc_(genshin_impact)',
    'джинн': 'jean_(genshin_impact)',
    'сахароза': 'sucrose_(genshin_impact)',
    'чунюнь': 'chongyun_(genshin_impact)',
    'ноэлль': 'noelle_(genshin_impact)',
    'беннет': 'bennett_(genshin_impact)',
    'фишль': 'fischl_(genshin_impact)',
    'нингуан': 'ningguang_(genshin_impact)',
    'синцю': 'xingqiu_(genshin_impact)',
    'бейдоу': 'beidou_(genshin_impact)',
    'сянлин': 'xiangling_(genshin_impact)',
    'рейзор': 'razor_(genshin_impact)',
    'барбара': 'barbara_(genshin_impact)',
    'лиза': 'lisa_(genshin_impact)',
    'кэйа': 'kaeya_(genshin_impact)',
    'эмбер': 'amber_(genshin_impact)',
    'люмин': 'lumine_(genshin_impact)',
    'итер': 'aether_(genshin_impact)',
    'паймон': 'paimon_(genshin_impact)',
    'эола': 'eula_(genshin_impact)',
    'яньфей': 'yanfei_(genshin_impact) ',
    'аяка': 'kamisato_ayaka',
    'йоимия': 'yoimiya_(genshin_impact)',
    'казуха': 'kaedehara_kazuha',
    'кокоми': 'sangonomiya_kokomi',
    'сара': 'kujou_sara',
    'райден': 'raiden_shogun',
    'саю': 'sayu_(genshin_impact)',
    'тома': 'thoma_(genshin_impact)',
    'горо': 'gorou_(genshin_impact)',
    'яэмико': 'yae_miko_(genshin_impact)',
    'юньцзинь': 'yun_jin_(genshin_impact)',
    'шэньхэ': 'shenhe_(genshin_impact)',
    'итто': 'arataki_itto',
    'аято': 'kamisato_ayato',
    'елань': 'yelan_(genshin_impact)',
    'куки': 'kuki_shinobu',
    'синобу': 'kuki_shinobu',
    'кукисинобу': 'kuki_shinobu',
    'байчжу': 'baizhu_(genshin_impact)',
    'скарамучча': 'scaramouche_(genshin_impact)',
    'яояо': 'yaoyao_(genshin_impact)',
    'хэйдзо': 'shikanoin_heizou',
    'сайно': 'cyno_(genshin_impact)',
    'синьора': 'signora_(genshin_impact)',
    'дори': 'dori_(genshin_impact)',
    'коллеи': 'collei_(genshin_impact)'
}

ART_STYLE = {
    'реализм': 'realistic',
    'фотореализм': 'photorealistic',
    'монохром': 'monochrome',
    'портрет': 'portrait',
    'мульт': 'cartoon',
    'комикс': 'comic',
    'лайнарт': 'lineart'
}

CLOTHING = {
    'одежда': 'clothing',
    'шляпа': 'hat',
    'свитер': 'sweater',
    'носки': 'socks',
    'кроссовки': 'sneakers',
    'чулки': 'thighhighs',
    'колготки': 'pantyhose',
    'перчатки': 'gloves',
    'платье': 'dress',
    'юбка': 'skirt',
    'штаны': 'pants',
    'джинсы': 'jeans',
    'мини-юбка': 'miniskirt',
    'бант': 'ribbon',
    'бабочка': 'bow',
    'бикини': 'bikini',
    'бюстгальтер': 'bra',
    'пиджак': 'jacket',
    'куртка': 'coat',
    'кофта': 'shirt',
    'очки': 'sunglasses',
    'каблуки': 'high_heels',
    'юката': 'yukata',
    'кимоно': 'kimono',
    'хаори': 'haori'
}

JEWELRY = {
    'украшения': 'jewelry',
    'серьги': 'earrings',
    'браслет': 'bracelet',
    'армлет': 'armlet',
    'анклет': 'anklet',
    'цепочка': 'necklace',
    'корона': 'crown',
    'тиара': 'tiara',
    'диадема': 'diadem',
    'заколка': 'hairpin',
    'чокер': 'choker',
    'пирсинг': 'piercing'
}

EMOTIONS = {
    'ахегао': 'ahegao',
    'гесугао': 'gesugao',
    'румянец': 'blush',
    'улыбка': 'smile',
    'радость': 'happy',
    'грусть': 'sad',
    'злость': 'angry',
    'недовольство': 'annoyed',
    'слезы': 'tears'
}

BODY = {
    'пальцы_ног': 'toes',
    'ноги': 'legs',
    'руки': 'hands',
    'стопы': 'feet',
    'бедра': 'thighs',
    'подмышки': 'armpits',
    'грудь': 'breasts',
    'попа': 'ass',
    'зубы': 'teeth',
    'клыки': 'fang',
    'ключицы': 'clavicle',
    'живот': 'navel',
    'талия': 'waist',
    'язык': 'tongue',
    'губы': 'lips',
    'челка': 'bangs',
    'рожки': 'horns',
    'веснушки': 'freckles',
    'гетерохромия': 'heterochromia'
}

CREATURES = {
    'демон': 'demon_boy',
    'демонесса': 'demon_girl',
    'дракон': 'dragon_boy',
    'драконесса': 'dragon_girl',
    'ангелы': 'angel',
    'демоны': 'demon',
    'вампиры': 'vampire',
    'эльфы': 'elf',
    'феи': 'fairy',
    'некомими': 'nekomimi',
    'китсунемими': 'kitsunemimi',
    'инумими': 'inumimi',
    'фурри': 'furry'
}
